version: '3'
services:
  mlflow:
    build:
      context: ./mlflow_docker
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:                            
      - AWS_ACCESS_KEY_ID=****
      - AWS_SECRET_ACCESS_KEY=***
      - AWS_DEFAULT_REGION=****
    command: mlflow server --default-artifact-root s3://mlopsbucketantihaddock --host 0.0.0.0 --port 8000
    networks:
      - mynetwork
  flaskapp:
    build:
      context: ./flask_docker
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:                            
      - AWS_ACCESS_KEY_ID=***
      - AWS_SECRET_ACCESS_KEY=***
      - AWS_DEFAULT_REGION=***
    networks:
      - mynetwork

networks:
  mynetwork:
