version: '3'
services:
  mlflow:
    build:
      context: ./mlflow_docker
      dockerfile: Dockerfile
    container_name: mlflow-container
    ports:
      - 8000:8000
    environment:                            
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - AWS_DEFAULT_REGION=${region}
    networks:
      - mynetwork
  flaskapp:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: flask-container
    ports:
      - 5000:5000
    environment:                            
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - AWS_DEFAULT_REGION=${region}
    networks:
      - mynetwork

networks:
  mynetwork:
